/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.ClienteCON;
import modelo.EntPeliculas;
/**
 *
 * @author Angel-Alcv
 */
public class Peliculas extends javax.swing.JInternalFrame {
ClienteCON ccon=new ClienteCON();
EntPeliculas pel=new EntPeliculas();
     
    DefaultTableModel modelo=new DefaultTableModel();
    int ip;
    /**
     * Creates new form Peliculas
     */
    public Peliculas() {
        initComponents();
        listarP();
    }
void listarP(){
    List<EntPeliculas> lista=ccon.listarPeli();
    modelo=(DefaultTableModel)TablaPeli.getModel();
    Object[]ob=new Object[5];
    for (int i = 0; i < lista.size() ; i++) {
        ob[0]=lista.get(i).getIdp();
        ob[1]=lista.get(i).getCo();
        ob[2]=lista.get(i).getNop();
        ob[3]=lista.get(i).getPre();
        ob[4]=lista.get(i).getStok();
        
        modelo.addRow(ob);
    }
     TablaPeli.setModel(modelo);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        txtStock = new javax.swing.JTextField();
        Agregarpeli = new javax.swing.JButton();
        ActualizarPeli = new javax.swing.JButton();
        EliminarPeli = new javax.swing.JButton();
        NuevoPeli = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtNomP = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaPeli = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setTitle("Producto");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Nombre");

        jLabel2.setText("Precio");

        jLabel3.setText("Stock");

        Agregarpeli.setBackground(new java.awt.Color(11, 127, 70));
        Agregarpeli.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Agregarpeli.setForeground(new java.awt.Color(255, 255, 255));
        Agregarpeli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/guardar.png"))); // NOI18N
        Agregarpeli.setText("  AGREGAR    ");
        Agregarpeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarpeliActionPerformed(evt);
            }
        });

        ActualizarPeli.setBackground(new java.awt.Color(11, 124, 68));
        ActualizarPeli.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ActualizarPeli.setForeground(new java.awt.Color(255, 255, 255));
        ActualizarPeli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/actualizar.png"))); // NOI18N
        ActualizarPeli.setText(" ACTUALIZAR");
        ActualizarPeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarPeliActionPerformed(evt);
            }
        });

        EliminarPeli.setBackground(new java.awt.Color(255, 43, 43));
        EliminarPeli.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        EliminarPeli.setForeground(new java.awt.Color(255, 255, 255));
        EliminarPeli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/eliminar.png"))); // NOI18N
        EliminarPeli.setText("  ELIMINAR  ");
        EliminarPeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarPeliActionPerformed(evt);
            }
        });

        NuevoPeli.setBackground(new java.awt.Color(11, 124, 68));
        NuevoPeli.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        NuevoPeli.setForeground(new java.awt.Color(255, 255, 255));
        NuevoPeli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/nuevo.png"))); // NOI18N
        NuevoPeli.setText("    NUEVO     ");
        NuevoPeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoPeliActionPerformed(evt);
            }
        });

        jLabel5.setText("Codigo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(txtStock)
                    .addComponent(txtCodigo)
                    .addComponent(txtNomP))
                .addGap(68, 68, 68)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ActualizarPeli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NuevoPeli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EliminarPeli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Agregarpeli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Agregarpeli)
                    .addComponent(jLabel5)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(ActualizarPeli)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EliminarPeli)
                        .addGap(3, 3, 3)
                        .addComponent(NuevoPeli))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(txtNomP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        TablaPeli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IDPRODUCTO", "CODIGO", "NOMBRE", "PRECIO", "STOCK"
            }
        ));
        TablaPeli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaPeliMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaPeli);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton1.setBackground(new java.awt.Color(255, 43, 43));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/sal.png"))); // NOI18N
        jButton1.setText("SALIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EliminarPeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarPeliActionPerformed
        // TODO add your handling code here:
         eliminarP();
        limpiarP();
        listarP();
        nuevoP();
    }//GEN-LAST:event_EliminarPeliActionPerformed

    private void NuevoPeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoPeliActionPerformed
        // TODO add your handling code here:
         nuevoP();
        limpiarP();
        listarP();
        nuevoP();
    }//GEN-LAST:event_NuevoPeliActionPerformed

    private void TablaPeliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaPeliMouseClicked
        // TODO add your handling code here:
        int fila=TablaPeli.getSelectedRow();
        if (fila==-1) {
            JOptionPane.showMessageDialog(this, "Debe Selecionar una Fila");
             
        }else{
    ip= Integer.parseInt(TablaPeli.getValueAt(fila,0).toString());
     String co=TablaPeli.getValueAt(fila,1).toString();
     String np=TablaPeli.getValueAt(fila,2).toString();
     String pp=TablaPeli.getValueAt(fila,3).toString();
     String st=TablaPeli.getValueAt(fila,4).toString();
    
     txtCodigo.setText(co);
     txtNomP.setText(np);
     txtPrecio.setText(pp);
     txtStock.setText(st);
    
       
        }
    }//GEN-LAST:event_TablaPeliMouseClicked

    private void AgregarpeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarpeliActionPerformed
        // TODO add your handling code here:
         agregarP();
        limpiarP();
        listarP();
        nuevoP();
    }//GEN-LAST:event_AgregarpeliActionPerformed

    private void ActualizarPeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarPeliActionPerformed
        // TODO add your handling code here:
         actualizarP();
        limpiarP();
        listarP();
        nuevoP();
    }//GEN-LAST:event_ActualizarPeliActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

     void agregarP(){
     String co=txtCodigo.getText();
     String np=txtNomP.getText();
     String pp=txtPrecio.getText();
     String st=txtStock.getText();
     
     Object[] ob=new Object[4];
     ob[0]=co;
     ob[1]=np;
     ob[2]=pp;
     ob[3]=st;
     
     ccon.addPeli(ob);
     }
     
     void actualizarP(){
     int fila=TablaPeli.getSelectedRow();
         if (fila==-1) {
             JOptionPane.showMessageDialog(this,"Por favor selecione una fila para continuear");
         }else{
     String co=txtCodigo.getText();
     String np=txtNomP.getText();
     String pp=txtPrecio.getText();
     String st=txtStock.getText();
    
     Object[] obp=new Object[5];
     obp[0]=co;
     obp[1]=np;
     obp[2]=pp;
     obp[3]=st;
     obp[4]=ip;
     ccon.actualizarPeli(obp);
        }
     }
     void eliminarP(){
     int fila=TablaPeli.getSelectedRow(); 
         if (fila==-1) {
             JOptionPane.showMessageDialog(this,"Por favor selecione una fila para continuear");
         }else{
           int ids=Integer.parseInt(TablaPeli.getValueAt(fila,0).toString());
           ccon.eliminarPeli(ids);
         }
     }
     
     void nuevoP(){
     
     txtCodigo.setText("");    
     txtNomP.setText("");
     txtPrecio.setText("");
     txtStock.setText(""); 
     txtCodigo.requestFocus();
     
     }
     
     void limpiarP(){
         for (int i = 0; i < modelo.getRowCount(); i++) {
             modelo.removeRow(i);
             i=i-1;
         }
     }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActualizarPeli;
    private javax.swing.JButton Agregarpeli;
    private javax.swing.JButton EliminarPeli;
    private javax.swing.JButton NuevoPeli;
    private javax.swing.JTable TablaPeli;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNomP;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtStock;
    // End of variables declaration//GEN-END:variables
}
